# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-05 23:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181105_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentContent', models.TextField(help_text='Enter comment', max_length=1000)),
                ('commentScore', models.IntegerField()),
                ('commentDateTime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['commentDateTime'],
            },
        ),
        migrations.CreateModel(
            name='FoodPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postScore', models.IntegerField()),
                ('location', models.CharField(help_text='Enter coords for the food', max_length=1000)),
                ('postDate', models.DateTimeField(blank=True, null=True)),
                ('postInfo', models.CharField(default='Food is here', help_text='Enter info about the food', max_length=1000)),
                ('postUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['postDate'],
            },
        ),
        migrations.AddField(
            model_name='foodcomment',
            name='commentPost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.FoodPost'),
        ),
        migrations.AddField(
            model_name='foodcomment',
            name='commenter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
