# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-26 20:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181105_2311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(help_text='Enter coords for the food', max_length=1000)),
                ('commentPost', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.FoodPost')),
                ('postUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
