# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-12-05 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodpost',
            name='location',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='foodpost',
            name='postInfo',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='foodpost',
            name='postScore',
            field=models.IntegerField(default=0),
        ),
    ]
