# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-12-05 22:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20181205_2226'),
        ('users', '0005_auto_20181203_2244'),
    ]

    operations = [
    ]
