# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-12-11 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_merge_20181205_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodpost',
            name='foodType',
            field=models.TextField(default='Pizza', max_length=40, verbose_name='Food'),
        ),
        migrations.AlterField(
            model_name='foodpost',
            name='location',
            field=models.CharField(choices=[('library', 'W.E.B. Du Bois Library'), ('hamp', 'Hampshire Dining Hall'), ('berk', 'Berkshire Dining Hall'), ('woo', 'Worcester Dining Hall'), ('frank', 'Franklin Dining Hall'), ('l', 'Lederle Tower'), ('Sc', 'South College'), ('rec', 'Campus Rec Center'), ('cs', 'Computer Science Building'), ('Thom', 'Thompson'), ('mor', 'Morrill 3')], max_length=100, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='foodpost',
            name='postDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='foodpost',
            name='postInfo',
            field=models.TextField(max_length=1000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='foodpost',
            name='postScore',
            field=models.IntegerField(default=0, verbose_name='Score'),
        ),
        migrations.AlterField(
            model_name='foodpost',
            name='roomNum',
            field=models.IntegerField(default=0, verbose_name='Room Number'),
        ),
    ]
