# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-12-11 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20181211_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodpost',
            name='foodType',
            field=models.CharField(default='this', max_length=40, verbose_name='Food'),
        ),
    ]
