# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-12-11 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20181211_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodpost',
            name='foodPic',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
