# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-12-11 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20181211_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodpost',
            name='foodPic',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Picture'),
        ),
        migrations.AlterField(
            model_name='foodpost',
            name='location',
            field=models.CharField(choices=[('W.E.B. Du Bois Library', 'W.E.B. Du Bois Library'), ('Hampshire Dining Hall', 'Hampshire Dining Hall'), ('Berkshire Dining Hall', 'Berkshire Dining Hall'), ('Worcester Dining Hall', 'Worcester Dining Hall'), ('Franklin Dining Hall', 'Franklin Dining Hall'), ('Lederle Tower', 'Lederle Tower'), ('South College', 'South College'), ('Campus Rec Center', 'Campus Rec Center'), ('Computer Science Building', 'Computer Science Building'), ('Thompson', 'Thompson'), ('Morrill 3', 'Morrill 3')], max_length=100, verbose_name='Location'),
        ),
    ]
