# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-12-11 22:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20181211_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodpost',
            name='foodPic',
        ),
    ]
