# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-12-12 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_remove_foodpost_foodpic'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='userScore',
            field=models.IntegerField(default=0),
        ),
    ]
