# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-12-12 16:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_person_userscore'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodpost',
            options={'ordering': ['postScore']},
        ),
    ]
