# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-12-12 17:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20181212_1631'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodpost',
            options={'ordering': ['-postScore']},
        ),
    ]
